- name: Preinstall
  hosts: all
  become: true
  tasks:
    - name: "Template configured nameservers to resolv.conf for Kubespray slurp"
      ansible.builtin.template:
        src: "./resolv.conf.j2"
        dest: "/etc/resolv.conf"
        force: true
      vars:
        dns_servers:
          - "10.0.3.10"
          - "10.0.3.11"
    # - name: "Install local stub resolver (systemd-resolved)"
    #   ansible.builtin.file:
    #     src: "/run/systemd/resolve/stub-resolv.conf"
    #     dest: "/etc/resolv.conf"
    #     state: "link"
    #     owner: "root"
    #     group: "root"
    #     force: true
