- name: Preinstall
  hosts: all
  become: true
  tasks:
    - name: "Install local stub resolver (systemd-resolved)"
      ansible.builtin.file:
        src: "/run/systemd/resolve/stub-resolv.conf"
        dest: "/etc/resolv.conf"
        state: "link"
        owner: "root"
        group: "root"
        force: true
