all:
  hosts:
    k8s1.private.swifthomelab.net: {}
    k8s2.private.swifthomelab.net: {}
    k8s3.private.swifthomelab.net: {}
    k8s4.private.swifthomelab.net: {}
    k8s5.private.swifthomelab.net: {}
  children:
    kube_control_plane:
      hosts:
        k8s1.private.swifthomelab.net: {}
        k8s2.private.swifthomelab.net: {}
    kube_node:
      hosts:
        k8s1.private.swifthomelab.net: {}
        k8s2.private.swifthomelab.net: {}
        k8s3.private.swifthomelab.net: {}
        k8s4.private.swifthomelab.net: {}
        k8s5.private.swifthomelab.net: {}
    etcd:
      hosts:
        k8s1.private.swifthomelab.net: {}
        k8s2.private.swifthomelab.net: {}
        k8s3.private.swifthomelab.net: {}
    k8s_cluster:
      children:
        kube_control_plane: {}
        kube_node: {}
    calico_rr:
      hosts: {}
